"""add tag

Revision ID: b0c7eab768ff
Revises: aba173299803
Create Date: 2026-05-20 18:14:36.964663

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b0c7eab768ff'
down_revision: Union[str, None] = 'aba173299803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###
    ### Add tag entries in the database
    op.execute(
        sa.text(
        """
        INSERT INTO tag (id, name, instructions) VALUES
        (gen_random_uuid(), 'EXPRESS', 'Handle with priority - deliver within 24 hours'),
        (gen_random_uuid(), 'STANDARD', 'Regular delivery within 3-5 business days'),
        (gen_random_uuid(), 'FRAGILE', 'Handle with care - fragile contents'),
        (gen_random_uuid(), 'HEAVY', 'Heavy shipment - use appropriate equipment'),
        (gen_random_uuid(), 'INTERNATIONAL', 'International shipment - customs documentation required'),
        (gen_random_uuid(), 'DOMESTIC', 'Domestic delivery only'),
        (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Keep at controlled temperature during transport'),
        (gen_random_uuid(), 'GIFT', 'Gift shipment - handle with care, no invoice visible'),
        (gen_random_uuid(), 'RETURN', 'Return shipment - process accordingly'),
        (gen_random_uuid(), 'DOCUMENTS', 'Contains important documents - keep dry and flat')
        """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
